<?php
include_once 'Circle.php';

class Cylinder extends Circle
{
public $height;
public function __construct($_name, $_radius,$_height)
{
    parent::__construct($_name, $_radius);
    $this->height=$_height;
}
public function calculateArea()
{
    return parent::calculateArea()+parent::calculatePerimeter()*$this->height; // TODO: Change the autogenerated stub
}
public function calculateVolume(){
    return parent::calculateArea()*$this->height;
}
}